services:
  jin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jin
    entrypoint: "/bin/bash -c 'npm i ; tail -f /dev/null'"
    init: true
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - .:/jin
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /jin
    user: root
    networks:
      - supabase_default

networks:
  supabase_default:
    external: true
# 開発用DB
# jin_db:
#   build:
#     context: .
#     dockerfile: ./db/Dockerfile
#   container_name: jin_db
#   ports:
#     - 5432:5432
#   environment:
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: password
#     POSTGRES_DB: jin_db
#   restart: always
#   volumes:
#     - ./db/data:/var/lib/postgresql/data
#     - ./db/pg_hba.conf:/etc/postgresql/main/pg_hba.conf
