services:
  jin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jin
    entrypoint: "/bin/sh -c 'npm install && /bin/sh'"
    init: true
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/root/jin
    working_dir: /root/jin
    user: root

  # 開発用DB
  jin_db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
